import type { ToolDef } from '@compass_agents/core'
import { z } from 'zod'
import type { FetchImpl } from './venice-brain'
import { VENICE_BASE_URL } from './wire'

/** Persist generated bytes (image/audio) and return where they landed. */
export type SaveMedia = (name: string, bytes: Uint8Array) => string | Promise<string>

export interface VeniceMediaOpts {
  apiKey: string
  baseUrl?: string
  fetchImpl?: FetchImpl
  /** Image model id; resolve current ids via GET /models. */
  imageModel?: string
  /** Vision-capable chat model id (for venice.vision). */
  visionModel?: string
  /** TTS model id + voice (for venice.speak). */
  speechModel?: string
  voice?: string
  /** Where to persist generated media; without it the tools just report success. */
  save?: SaveMedia
}

export interface ImageRequest {
  model: string
  prompt: string
  aspect_ratio: string
  resolution: string
}

export function buildImageRequest(
  args: { prompt: string; aspectRatio?: string },
  model: string,
): ImageRequest {
  return {
    model,
    prompt: args.prompt,
    aspect_ratio: args.aspectRatio ?? '1:1',
    resolution: '1K',
  }
}

/** Decode a base64 (optionally data-URI) string to bytes. */
export function decodeBase64(b64: string): Uint8Array {
  const clean = b64.includes(',') ? b64.slice(b64.indexOf(',') + 1) : b64
  const bin = atob(clean)
  const out = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
  return out
}

const ImageArgs = z.object({
  prompt: z.string().min(1).describe('What to draw.'),
  aspectRatio: z.string().optional().describe('e.g. "16:9", "1:1". Default 1:1.'),
})

/**
 * `venice.image` — generate an image via Venice's `/image/generate`. Saves the
 * result (when a `save` sink is wired) and reports the path. Registering it makes
 * Venice a multi-endpoint, "core" part of the agent.
 */
export function makeVeniceImageTool(opts: VeniceMediaOpts): ToolDef<z.infer<typeof ImageArgs>> {
  const baseUrl = (opts.baseUrl ?? VENICE_BASE_URL).replace(/\/+$/, '')
  const f = opts.fetchImpl ?? fetch
  const model = opts.imageModel ?? 'gpt-image-2'
  return {
    name: 'venice.image',
    description: 'Generate an image from a text prompt via Venice.',
    schema: ImageArgs,
    run: async args => {
      const res = await f(`${baseUrl}/image/generate`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${opts.apiKey}` },
        body: JSON.stringify(buildImageRequest(args, model)),
      })
      if (!res.ok) return { content: `venice image error ${res.status}`, ok: false }
      const json = (await res.json()) as { images?: string[] }
      const imgs = json.images ?? []
      if (imgs.length === 0) return { content: 'venice returned no image', ok: false }
      if (opts.save) {
        const paths: string[] = []
        for (let i = 0; i < imgs.length; i++) {
          paths.push(await opts.save(`image-${Date.now()}-${i}.png`, decodeBase64(imgs[i]!)))
        }
        const n = paths.length
        return { content: `${n} image${n > 1 ? 's' : ''} saved → ${paths.join(', ')}`, ok: true }
      }
      return { content: `generated ${imgs.length} image(s) for: ${args.prompt}`, ok: true }
    },
  }
}

const VisionArgs = z.object({
  imageUrl: z.string().min(1).describe('URL (or data URI) of the image to analyze.'),
  prompt: z.string().optional().describe('What to ask about the image. Default: describe it.'),
})

/** `venice.vision` — analyze/describe an image via a Venice vision model. */
export function makeVeniceVisionTool(opts: VeniceMediaOpts): ToolDef<z.infer<typeof VisionArgs>> {
  const baseUrl = (opts.baseUrl ?? VENICE_BASE_URL).replace(/\/+$/, '')
  const f = opts.fetchImpl ?? fetch
  const model = opts.visionModel ?? 'qwen-2.5-vl'
  return {
    name: 'venice.vision',
    description: 'Look at an image (by URL) and answer a question about it, via Venice vision.',
    schema: VisionArgs,
    run: async args => {
      const res = await f(`${baseUrl}/chat/completions`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${opts.apiKey}` },
        body: JSON.stringify({
          model,
          messages: [
            {
              role: 'user',
              content: [
                { type: 'text', text: args.prompt ?? 'Describe this image in detail.' },
                { type: 'image_url', image_url: { url: args.imageUrl } },
              ],
            },
          ],
        }),
      })
      if (!res.ok) return { content: `venice vision error ${res.status}`, ok: false }
      const json = (await res.json()) as {
        choices?: Array<{ message?: { content?: string } }>
      }
      const text = json.choices?.[0]?.message?.content ?? ''
      return { content: text || '(no description)', ok: !!text }
    },
  }
}

const SpeechArgs = z.object({
  text: z.string().min(1).describe('The text to speak.'),
  voice: z.string().optional().describe('Voice id; defaults to the configured voice.'),
})

/** `venice.speak` — text-to-speech via Venice's `/audio/speech`. Saves the audio. */
export function makeVeniceSpeechTool(opts: VeniceMediaOpts): ToolDef<z.infer<typeof SpeechArgs>> {
  const baseUrl = (opts.baseUrl ?? VENICE_BASE_URL).replace(/\/+$/, '')
  const f = opts.fetchImpl ?? fetch
  const model = opts.speechModel ?? 'tts-kokoro'
  return {
    name: 'venice.speak',
    description: 'Turn text into spoken audio via Venice text-to-speech.',
    schema: SpeechArgs,
    run: async args => {
      const res = await f(`${baseUrl}/audio/speech`, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${opts.apiKey}` },
        body: JSON.stringify({
          model,
          input: args.text,
          voice: args.voice ?? opts.voice ?? 'af_sky',
          response_format: 'mp3',
        }),
      })
      if (!res.ok) return { content: `venice speech error ${res.status}`, ok: false }
      const bytes = new Uint8Array(await res.arrayBuffer())
      if (opts.save) {
        const path = await opts.save(`speech-${Date.now()}.mp3`, bytes)
        return { content: `audio saved (${bytes.length} bytes) → ${path}`, ok: true }
      }
      return { content: `generated ${bytes.length} bytes of audio`, ok: true }
    },
  }
}

/** All Venice media tools — image generation, vision, and speech. */
export function makeVeniceMediaTools(opts: VeniceMediaOpts): ToolDef[] {
  return [
    makeVeniceImageTool(opts) as ToolDef,
    makeVeniceVisionTool(opts) as ToolDef,
    makeVeniceSpeechTool(opts) as ToolDef,
  ]
}
